Always allow key creation where less than 2 exist
kneemaa/github-action-rotate-aws-secrets pull request #22
Opened 2022-02-15 14:56 UTC by leigh-hogarth

2022-02-20 16:52 UTC, kneemaa commented
@leigh-hogarth What is the use case for this? In what scenario would the repository have 0 keys and would update itself to have keys?

2022-02-22 11:41 UTC, leigh-hogarth commented
Hi @kneemaa - there are instances where an IAM user can be created without any pre-existing access keys.
For example, if you were to create an IAM user via a tool such as Terraform, due to key rotation you wouldn't want to create the access keys using the same tool. Therefore the result is an initial empty user.
This action in its original state will then fail unless you manually create an initial set of keys, which is why I created this PR to allow for the use-case and avoid needing manual intervention.

2022-02-25 04:05 UTC, kneemaa commented
@leigh-hogarth - if the user has no keys, how will it's first set of keys be set in Github?

2022-02-28 10:19 UTC, leigh-hogarth commented
@kneemaa they won't be. This change allows you start from scratch with an empty IAM user and empty GH secrets.

2022-03-02 16:38 UTC, kneemaa commented
@leigh-hogarth I do not see what is resolving. 

The Action will not work until Keys are set and accessible.

Having this action run when there are no keys is not desired, having it fail when no keys are found is a way to alert that your other actions will fail because there are no valid keys.

2022-03-07 14:37 UTC, leigh-hogarth commented
@kneemaa the use case is there for setting things up from scratch.
The action _does_ work without those keys being present as we actually use it in a central workflow which manages these keys on other repositories.
Therefore so long as that central workflow has AWS access, it can run this action against other repositories.
Those other repositories may be in an infant state, so will not have keys set as secrets on first run, hence why this update allows for that.

2022-03-09 00:26 UTC, kneemaa commented
@leigh-hogarth Thanks for the clarification, could you please update the README to account for this and how it works?

2022-03-15 09:19 UTC, leigh-hogarth commented
@kneemaa README updated.

2022-03-16 01:26 UTC, kneemaa commented on rotate_keys.py
> +        print(f"Validated <2 keys exist ({starting_num_keys}), proceeding.")
This is going to print as `Validated <2 keys exist 0, proceeding.` or `Validated <2 keys exist 1, proceeding.`

Suggesting the print be updated to have `{starting_num_keys}` removed or the output to be clear

2022-03-16 01:29 UTC, kneemaa commented on README.md
> +1. If 0 or 1 set of keys exists, the action will:
This needs to be clear that having 0 keys will not work if the action is run in the Target repository (original functionality)

https://github.com/kneemaa/github-action-rotate-aws-secrets/pull/22#issuecomment-1060756380

2022-03-16 01:29 UTC, kneemaa requested changes
two requests

2022-03-22 14:06 UTC, leigh-hogarth commented on rotate_keys.py
> +        print(f"Validated <2 keys exist ({starting_num_keys}), proceeding.")
Updated the text in the latest commit

2022-03-22 14:07 UTC, leigh-hogarth commented on README.md
> +1. If 0 or 1 set of keys exists, the action will:
This is irrelevant. The action won't run without appropriate access keys on the repository and never would.

2022-03-31 00:04 UTC, merged